### ISSUE TITLE
Resource pack enabling issue

### ISSUE THREAD

**Issue by C0ADAE** [legopitstop/Lots-More-Food-Mods#13]
**What Edition of the mod are you using?** Herobrine mansion v2
The Minecraft platform that that issue is taking place: Java

**Describe the bug** I've downloaded the resource pack it appears in my pack menu but the map still says RP disabled

**To Reproduce** Install The map on a 1.16.3 server install the RP on your mc account 

**Expected behavior**

**Screenshots**
![Screenshot (145)](https://user-images.githubusercontent.com/79872774/109565252-09eb5480-7a97-11eb-8465-6209a853c9b3.png)
![Screenshot (146)](https://user-images.githubusercontent.com/79872774/109565263-0e177200-7a97-11eb-97cb-7e92494a3e5f.png)
![Screenshot (147)](https://user-images.githubusercontent.com/79872774/109565268-0f489f00-7a97-11eb-8c16-4ba33de1cc3a.png)
![Screenshot (147)](https://user-images.githubusercontent.com/79872774/109565275-153e8000-7a97-11eb-9e90-6336ffedfef4.png)

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.1.0] 1.16.3
 - Mod Version [e.g. 22] v-2
 - OS: [e.g. iOS]Windows
 - Forge Version [e.g. 35]

**Smartphone (please complete the following information):**
 - Minecraft Version: [e.g. 1.1.0]
 - Mod Version [e.g. 22]

**Additional context**

**Comment by legopitstop** [comment]
Are you using the resourcepack provided inside the map or did you download the resourcepack through the datapack.

**Comment by C0ADAE** [comment]
I'm using the zip from the mao

**Comment by legopitstop** [comment]
Ok, Figured it out, weird Minecraft bug. Just relog from the world and it should say `Enabled`
