### ISSUE TITLE
 When i try to use seeds and trees from the addon they dont work but everything else works and im on 1.6.102/4

### ISSUE THREAD

**Issue by VikiBgg** [legopitstop/Lots-More-Food-Mods#15]
**What Edition of the mod are you using?**
The Minecraft platform that that issue is taking place:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.1.0]
 - Mod Version [e.g. 22]
 - Forge Version [e.g. 35]

**Smartphone (please complete the following information):**
 - Minecraft Version: [e.g. 1.1.0]
 - Mod Version [e.g. 22]

**Additional context**

**Comment by legopitstop** [comment]
Duplicated by [#14](https://github.com/legopitstop/Lots-More-Food-Mods/issues/14)
