### ISSUE TITLE
Multiplayer bug

### ISSUE THREAD

**Issue by CalangoLango** [legopitstop/Lots-More-Food-Mods#18]
I have a server in the realms, and when I do a backup of the save and put it back in the realms the mod stops working, nothing appears from it only the invalid blocks.

**Comment by legopitstop** [comment]
Closed until more info has been provided. Please use the [issue template](https://github.com/legopitstop/Lots-More-Food-Mods/issues/new?assignees=legopitstop&labels=bug+%3Abug%3A&template=bug_report.md&title=+) or reference the [example bug report](https://github.com/legopitstop/Lots-More-Food-Mods/issues/1) to provide useful information to get this bug fixed.
