### ISSUE TITLE
no data fixer for exotic trader causing forge to crash when i  boot up the mod

### ISSUE THREAD

**Issue by Josetheyoutuber** [legopitstop/Lots-More-Food-Mods#2]

**Comment by Josetheyoutuber** [comment]
i use 1.16.1

**Comment by legopitstop** [comment]
Thank you for your report!
However, this issue has been temporarily closed as It requires more information.

Please include more information including steps to reproduce the problem:

**Steps to Reproduce:**
1.
2.
3.

**Observed Results:**

**Expected Results:**

If your ticket does not look like the example given [here](https://github.com/legopitstop/Lots-More-Food-Mods/issues), then it's likely to be closed as incomplete.

**Comment by legopitstop** [comment]
Issue has been moved to [#3](https://github.com/legopitstop/Lots-More-Food-Mods/issues/3)
