### ISSUE TITLE
Sapling Glitcj

### ISSUE THREAD

**Issue by meli8123** [legopitstop/Lots-More-Food-Mods#23]
I commented this on the MCPE mod website but I'm gonna post a similar one here to. So, the only issue I have is with the saplings. They grow perfectly fine but the fruit themselves seem to be bugged. They randomly disappear from the leaves whenever I leave the area the trees are in or when I reload the world, so I'm only left with normal trees and no fruit. I've placed the trees near water and have spread them out so they're in an open space but that doesn't seem to have worked. I'm trying to make an apple tree orchard and it's hard when the apples keep disappearing.

**Comment by legopitstop** [comment]
Closed until more info has been provided. Please use the [issue template](https://github.com/legopitstop/Lots-More-Food-Mods/issues/new?assignees=legopitstop&labels=bug+%3Abug%3A&template=bug_report.md&title=+) or reference the [example bug report](https://github.com/legopitstop/Lots-More-Food-Mods/issues/1) to provide useful information to get this bug fixed.
