### ISSUE TITLE
When i jump to the seed planted all of the seed planted near it will break 

### ISSUE THREAD

**Issue by jerry447** [legopitstop/Lots-More-Food-Mods#24]
**What Edition of the mod are you using?**
The Minecraft platform that that issue is taking place:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.17.10.20]
 - Mod Version [e.g. 1.6.0]
 - OS: [e.g. android]
 - Forge Version [e.g. 35]

**Smartphone (please complete the following information):**
 - Minecraft Version: [e.g. 1.17.10.20]
 - Mod Version [e.g. 1.6.0]
 - OS: [e.g. android]

**Additional context**

**Comment by legopitstop** [comment]
Closed until more information is provided. Please complete the entire bug report. ie. Steps To Reproduce, Minecraft Edition you are experiencing the issue with.
