### ISSUE TITLE
Summer 2021 Lots More Food Addon Idea

### ISSUE THREAD

**Issue by PBrandon1629** [legopitstop/Lots-More-Food-Mods#26]
**Is your feature request related to a problem? Please describe.**
My feature request is related to a seasonal problem. Because this message was posted on 6/9/21 and June is summer month in the northern hemisphere, ice cold desserts and meals are going to be "popular." I know variety is amazing in the inventory, but I want MORE. The more means the better!

**Describe the solution you'd like**
As a sweet tooth, I prefer a unique arrangement of ice cream sandwiches. Using the ice cream flavors from the ice cream on a cone of the LMFA (Lots More Food Addon), I'm thinking about combining ice cream flavors for an ice cream sandwich in a crafting recipe if anyone adores 3 flavors in a creamy, cold, soft, tasty "sandwich."

**Describe alternatives you've considered**
I've considered something else than ice cream sandwiches. Maybe a few unique bowls of ice cream sundae and dipped ice cream on a sugar ice cream cone. If possible, ice cream bars would be nice like the ones from Popsicle (brand name).

**Additional context**
All flavors are based on the ice cream flavors used in the Lots More Food Addon. There may be a rare chance of freeze damage, but it's an option there if someone overdoses on ice cream sandwiches or other treats given in this message.

**Prefered Edition**
Could be both editions as I want both editions to have a fair share of the addon.

**Comment by legopitstop** [comment]
Closing this issue as I've added **Ice Cream Sandwiches** and **Ice Cream Bars** to the Google Sheet to track these ideas.
