### ISSUE TITLE
(B.E) Addon Broken on Minecraft Bedrock Realms

### ISSUE THREAD

**Issue by BlueWolf1315** [legopitstop/Lots-More-Food-Mods#28]
The addon doesnt work on realms please fix it

> cannot plant seeds or saplings - [Mr.Bigfoot](https://mcpedl.com/lots-more-food-bedrock-addon/) from MCPEDL

**Comment by BlueWolf1315** [comment]
it only stopped working in 1.17

**Comment by legopitstop** [comment]
Please provide more information. Use the template as a reference. https://github.com/legopitstop/Lots-More-Food-Mods/issues/1

**Comment by Jabbey92** [comment]
To be honest there's really no other details to give. I put it on my realm's world. It works fine when single player then after uploading the same world to a realm the items don't show it's as if the pack isn't active on the world.

**Comment by legopitstop** [comment]
Providing the pack version, and Minecraft version may come in handy. Also, try deleting the pack and reinstalling it.
