### ISSUE TITLE
(F.E) no data fixer for exotic trader in minecraft 1.16.1

### ISSUE THREAD

**Issue by Josetheyoutuber** [legopitstop/Lots-More-Food-Mods#3]
**What Edition of the mod are you using?**
The Minecraft platform that that issue is taking place:
 I am using Minecraft java for windows 10.
Minecraft Java Edition [Forge Edition]

**Describe the bug**
Minecraft crashes upon startup.

**To Reproduce**
1. Go to 'logs file after the mod fails to boot hence an error'
2. Click on 'latest log'
3. Scroll down to 'the very bottom'
4. See the error

**Expected behavior**
Minecraft loads up with the mod working.

**Desktop (please complete the following information):**
 - Minecraft Version:1.16.1
 - Mod Version:1.16.1-1.0.1
 - OS: [e.g. iOS]:windows 10
 - Forge Version [e.g. 35]:32.something the most recent version of it

**Comment by Josetheyoutuber** [comment]
[latest.log](https://github.com/legopitstop/Lots-More-Food-Mods/files/5631094/latest.log)

**Comment by legopitstop** [comment]
The exotic trader has been removed in newer versions.
