### ISSUE TITLE
Não consigo plantar nenhuma das safras e nem mudas de arvore 

### ISSUE THREAD

**Issue by OverHealth03** [legopitstop/Lots-More-Food-Mods#30]
**What Edition of the mod are you using?**
The Minecraft platform that that issue is taking place:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.1.0]
 - Mod Version [e.g. 22]
 - Forge Version [e.g. 35]

**Smartphone (please complete the following information):**
 - Minecraft Version: [e.g. 1.1.0]
 - Mod Version [e.g. 22]

**Additional context**
....

**Comment by legopitstop** [comment]
Please provide more information and properly fill out the bug report form.
