### ISSUE TITLE
(B.E) Certain items have the same textures.

### ISSUE THREAD

**Issue by PBrandon1629** [legopitstop/Lots-More-Food-Mods#35]
**What Edition of the mod are you using?**
The Minecraft platform that that issue is taking place: Bedrock, Mobile

**Describe the bug**
When inside of a world and checking out creative inventory, some appearance of items look like duplicates. I had Holiday Features on to find out the candies look like Black Candy.

**To Reproduce**
Steps to reproduce the [error] behavior:
1. Go to 'a creative world with food addon'
2. Click on 'inventory search bar,' then search
3. Scroll down to 'find duplicates of the same food with a different name'
4. See error.

**Expected behavior**
Expectation: Selecting a certain item looks different to others variants; selecting pies is one example.
Reality: See Screenshots.

**Screenshots**
https://cdn.discordapp.com/attachments/932672334509260861/941321273462640691/IMG_1172.png
https://cdn.discordapp.com/attachments/932672334509260861/941321273810772008/IMG_1171.png
https://cdn.discordapp.com/attachments/729445592236949575/941384586687033364/IMG_1173.png

**Smartphone (please complete the following information):**
 - Minecraft Version: 1.18.10
 - Mod Version: 1.1.7
 - OS: iOS (Mobile)

**Additional context**
I am unsure using the latest addon - from Weebly - resolves the resource pack error.

**Comment by legopitstop** [comment]
Fixed in v1.7.0-pre2
