### ISSUE TITLE
(B.E) wont let me plant any seeds 

### ISSUE THREAD

**Issue by gxthwitxh** [legopitstop/Lots-More-Food-Mods#37]
## What Edition of the mod are you using? 
The Minecraft platform that the issue is taking place, *Bedrock, Datapack, Forge*: bedrock

## Describe the bug
Won't let me plant any seeds anywhere
## Steps To Reproduce
Just on a normal world with my friend. He downloaded it on his pc and I joined the world on xbox and it won't let us plant the seeds even if I'm not on the world

## Smartphone / Desktop
 - Minecraft Version: [e.g. 1.18.2]
 - Mod Version [e.g. v1.2.0]
 - OS: [e.g. iOS, win10]

**Comment by legopitstop** [comment]
Need additional information: Minecraft Version, Mod Version and OS.

**Comment by gxthwitxh** [comment]
Bedrock, 1.19 and Microsoft

**Comment by legopitstop** [comment]
Also need the current version of the pack that you have installed.

**Comment by gxthwitxh** [comment]
It was the newest pack that's compatible with 1.19

**Comment by legopitstop** [comment]
In that version, we decided to use the new Fertile Soil block that you can place the crops on (This is until Mojang fixes a few issues with the farmland and custom blocks)

![screenshot](https://user-images.githubusercontent.com/40679582/181591293-5f987252-d3bf-423d-ae93-83aaf93b935d.png)
Recipe is an upside-down U shape of dirt, A water bucket in the middle with bonemeal on the bottom middle and should give you 7 Fertile Soil
