### ISSUE TITLE
(B.E) ADDON DOES NOT WORK ON BEDROCK v1.19.10.03

### ISSUE THREAD

**Issue by JudithGmz** [legopitstop/Lots-More-Food-Mods#38]
## What Edition of the mod are you using?
For Minecraft Bedrock.

## Describe the bug
Seeds and crops doesn't work anymore in Minecraft Bedrock V1.19.10.03 and textures of varient items seem to only have one texture (like all the donuts and juices have one texture only). Only recipes works. With crops of natural generation disappear from the local world and the seeds can't be planted, also with trees that doesn't generate and can't be planted.

## Steps To Reproduce
1. Create a world with the resource and behavior pack of the addon.
2. Set Holiday Creator Features in experimental gameplay ON.
3. Load the world.
4. Find a natural generation structure.
5. Realize that there aren't crops there except for the farming area and scarecrow.
6. Attempt to plant a seed obtained from the creative.
7. See that nothing happens.
(this apply also with trees)

## Expected behavior
1. Create a world with the resource and behavior pack of the addon.
2. Set Holiday Creator Features in experimental gameplay ON.
3. Load the world.
4. Find a natural generation structure.
5. Find random crops and take them.
6. Attempt to plant a seed obtained from the creative.
7. See how the seed can be placed without trouble.
(this apply also with trees)

## Screenshot
![image](https://user-images.githubusercontent.com/92896449/182034393-f305ef3c-02c0-4457-a40d-b1bc837c719c.png)
![image](https://user-images.githubusercontent.com/92896449/182034583-721ee199-0c09-4764-a73e-fac7f52facf8.png)

## Smartphone / Desktop
 - Minecraft Version: 1.19.10.03
 - Mod Version: 1.6.0
 - OS: Android, W10 (maybe also the others from bedrock).

## Additional context
I'll give you a content log file that I obtained from a server with only this addon added:
[ContentLog__Sunday__2022_July_31__15_23_36_1.txt](https://github.com/legopitstop/Lots-More-Food-Mods/files/9229210/ContentLog__Sunday__2022_July_31__15_23_36_1.txt)

**Comment by legopitstop** [comment]
v1.6.0 of Lot's More Food has not been updated for 1.17+. You will need to install the preview version of Lot's More Food for 1.19 (Also note that in this preview you can only place crops on the new fertile soil block) https://legopitstop.weebly.com/download.html?id=more_food_preview
