### ISSUE TITLE
(B.E) Wooden Tree Tap Not Working

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#39]
## What Edition of the mod are you using?
The Minecraft platform that the issue is taking place, *Bedrock, Datapack, Forge*:
1.19.20

## Describe the bug
When you place the wooden tree tap on a tree, you can see the sap falling to the ground. When you take a empty bucket to pick up the sap, you can hear it pick it up however nothing happens.

## Steps To Reproduce
1. 
2. 
3. 
4. 

## Smartphone / Desktop
 - Minecraft Version: [e.g. 1.18.2]
 - Mod Version [e.g. v1.2.0]
 - OS: [e.g. iOS, win10]

**Comment by legopitstop** [comment]
Please provide the pack version that you are using. Also, are there other players in the world when you are collecting the sap?

**Comment by SnowHuntsman** [comment]
v1.7.0-pre3 is the one we downloaded. Yes other players are in the world.

**Comment by legopitstop** [comment]
Thank you! Should be fixed in the next pre-release.
