### ISSUE TITLE
Japanese language data

### ISSUE THREAD

**Issue by mtripg6666tdr** [legopitstop/Lots-More-Food-Mods#4]
**Is your feature request related to a problem? Please describe.**
Not related to any problems

**Describe the solution you'd like**
I am moved by this mod, and I wanted to get this mod in japanese, so I just translated a resource pack of BE part of this mod as completely a volunteer. 
I created this Issue as a feature request because I hadn't known know if it's ok for me to create a pull request
Below is my lang file.
https://gist.github.com/mtripg6666tdr/748b6f2776460f5596bfd4ae0d17fde3
I will be glad if you also pack my lang file in a distribution of this mod, if you can.
Lastly, I can't speak English fluently since I usually use Japanese, I'm sorry for this comment that is hard to read...

**Describe alternatives you've considered**

**Additional context**

**Prefered Edition**
The Minecraft Edition you would like to see this feature added to.

**Comment by legopitstop** [comment]
Feel free to create a pull request.

**Comment by mtripg6666tdr** [comment]
In addition to that, this repo's contents is not up-to-date, many parts of this repo has changed in the most recent release.
I translated the most recent release of this mod, so in this mean, I can't create

**Comment by legopitstop** [comment]
Updated the bedrock edition files including the current 1.1.6 lang file. https://github.com/legopitstop/Lots-More-Food-Mods/tree/main/Lots%20More%20Food%20Addon/MoreFoodRP/texts

**Comment by mtripg6666tdr** [comment]
Thank you for updating and I just close this issue.
I will update lang file continously as best I can.
