### ISSUE TITLE
(B.E) Popcorn Not Working

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#41]
## What Edition of the mod are you using?
Bedrock, v1.7.0-pre3

## Describe the bug
The crafting table lists 1 corn, 1 empty popcorn bucket, and 1 lava bucket to craft a popcorn bucket. However, there is no recipe to craft a empty popcorn bucket. The recipe on the link shows to craft popcorn bucket you need 6 pieces of popcorn (made from putting corn on the cub in the furnace) 1 lava bucket and 1 empty bucket. That recipe is not listed in the crafting table for the v1.7.0-pre3. version of Lots More Food.

## Steps To Reproduce
1. 
2. 
3. 
4. 

## Smartphone / Desktop
 - Minecraft Version: [e.g. 1.18.2]
 - Mod Version [e.g. v1.2.0]
 - OS: [e.g. iOS, win10]

**Comment by legopitstop** [comment]
Thank you for your bug report. This issue has been added to #40
