### ISSUE TITLE
Unplacable saplings

### ISSUE THREAD

**Issue by Rexy0250** [legopitstop/Lots-More-Food-Mods#5]
**What Edition of the mod are you using?**
Bedrock

**Describe the bug**
I can't place any of the mods saplings, on any block

**Expected behavior**
I was expecting a sapling to be able to be placed, and grown into a tree, which for some reason ain't happening

**Screenshots**

**Smartphone (please complete the following information):**
 - Minecraft Version: 1.16.2
 - Mod Version: 0.0.6
 - OS: Android

**Comment by legopitstop** [comment]
Do you have experimental gameplay on, Mostly the Holiday Creator Features?
