### ISSUE TITLE
(B.E) Saplings and seeds won’t plant 

### ISSUE THREAD

**Issue by firestarcat** [legopitstop/Lots-More-Food-Mods#54]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

I am unable to plant any saplings or seeds, and I have even made sure the holiday experimental setting was on. 

### Steps To Reproduce

1. get a sapling
2.try to plant it

### Expected behavior

I expected it to plant like any other sapling or seed

### Minecraft Version

1.19

### Mod Version

1.6.0

### Platform

windows 11

**Comment by legopitstop** [comment]
Also, try using the Preview edition of Lot's More Food for 1.19 and up. https://legopitstop.weebly.com/download.html?id=more_food_preview
