### ISSUE TITLE
Tree Tap Not Working

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#57]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

When you place the tree tap, it is not producing sap for you to collect with a bucket. The tree tap in the creative menu appears different when you place it on the tree.

### Steps To Reproduce

1. Obtain tree tap from creative menu.
2. Place tree tap on tree 2 block.
...

### Expected behavior

When placing tree tap on tree, it should look like the tree tap in the inventory and produce sap. 

### Minecraft Version

1.19.73

### Mod Version

1.7.0-pre4

### Platform

Xbox S

**Comment by legopitstop** [comment]
The block model has not been fully added and will have a different, more 3D, model compared to the item. 

I will look into the tree tap not producing sap and will let you know how things go.

**Comment by legopitstop** [comment]
ok, I've tested it and it averages 7 minutes (4 min 11 max). Make sure you place the tree tap on logs, not wood.

**Comment by legopitstop** [comment]
Wooden Tree Taps now have a model and are working in [v1.7.0-pre5](https://more-food.fandom.com/wiki/Bedrock_Edition_1.7.0-pre5)
