### ISSUE TITLE
Raw Squid Uncraftable in Survival

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#58]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

Unable to obtain raw squid in survival mode.

### Steps To Reproduce

N/A
...

### Expected behavior

You should be able to obtain raw squid meat from (if possible, Squid) or combining fish in a crafting table if the Squid is unable to produce the raw meat.

### Minecraft Version

1.19.73

### Mod Version

1.7.0-pre4

### Platform

Xbox S

**Comment by legopitstop** [comment]
You can obtain raw squid by killing a Minecraft Squid. https://more-food.fandom.com/wiki/Raw_Squid#Obtaining
