### ISSUE TITLE
(B.E) Covered Apples Not Edible

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#60]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

White Chocolate Covered Apple, Dark Chocolate Covered Apple, and the Milk Chocolate Covered Apple is now edible. 

### Steps To Reproduce

1. Survival and low hunger.
2. On Xbox, LT to Eat the apple.
3. Nothing happens.
...

### Expected behavior

When hunger is low, eat the apple to regain hunger and health.

### Minecraft Version

1.19.83

### Mod Version

1.7.0-pre4

### Platform

Xbox

**Comment by SnowHuntsman** [comment]
After further investigation, the covered apples can be eaten, however there is no animation of the apple being eaten.

**Comment by legopitstop** [comment]
Fixed in [v1.7.0-pre5](https://more-food.fandom.com/wiki/Bedrock_Edition_1.7.0-pre5)
