### ISSUE TITLE
(B.E) Fertile soil not having a texture

### ISSUE THREAD

**Issue by Totoroangelo** [legopitstop/Lots-More-Food-Mods#64]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

In the side of the new block called Fertile Soil, there are no textures

### Steps To Reproduce

1.
2.
3.
...

### Expected behavior

Added a texture

### Minecraft Version

1.19.83

### Mod Version

1.7.0-pre4

### Platform

Huawei

**Comment by legopitstop** [comment]
Lot's More Food now requires Assets Plus (v1.3.0). If you're still having this issue with Assets Plus comment under this report and I will re-open it.
