### ISSUE TITLE
(B.E) Tomato Seeds are not planting on the Fertile Soil

### ISSUE THREAD

**Issue by Sniffles98** [legopitstop/Lots-More-Food-Mods#65]
### Describe the bug

The tomato seeds are not planting on the fertile soil like it should

### Steps To Reproduce

1. Put down soil
2. Get tomato seeds
3. Click to plant on soil
...

### Expected behavior

I expected it to plant it on the fertile soil like it should

### Minecraft Version

1.20

### Mod Version

Bedrock 

### Platform

Xbox, playstation,phones(android),switch, laptop (window 10/11)

**Comment by legopitstop** [comment]
Tomato Seeds are a type of bush meaning you can only place them on dirt and podzol. However, I decided to make it so you can place them on Fertile Soil in the next update.

**Comment by legopitstop** [comment]
Fixed in [v1.7.0-pre5](https://more-food.fandom.com/wiki/Bedrock_Edition_1.7.0-pre5)
