### ISSUE TITLE
(B.E) Wooden Tree Tap

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#66]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

When placing several wooden tree taps on trees, after some time, tree exploded. 

### Steps To Reproduce

1. Place wooden tree taps on tree
2. I had wooden tree tap on each side of the tree in different locations.
3. After some time, the tree busted completely (pieces of wood, wooden tree tap, etc basically exploded)
...

### Expected behavior

Place wooden tree tap. Tree doesn't explode.

### Minecraft Version

1.20.12

### Mod Version

1.7.0-pre4

### Platform

PC

### Additional context

This was for the 1.7.0 pre-5 pack.

**Comment by legopitstop** [comment]
Is this still affected even after enabling Molang features?
