### ISSUE TITLE
(B.E) Wooden Tree Tap Not Working

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#67]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

Wooden tree tap not working when placed on trees.

### Steps To Reproduce

1. Place wooden tree tap
2. Ticket speed set to 3
3. Wait 30 minutes, still no sap.
...

### Expected behavior

Sap producing from wooden tree tap to be collected with bucket.

### Minecraft Version

1.20.12

### Mod Version

1.7.0-pre4

### Platform

PC

### Additional context

With 1.7.0 pre5. Holiday experiment and custom biomes was enabled however wooden tree tap not working.

**Comment by legopitstop** [comment]
Are Molang Features enabled on the world/server?

**Comment by SnowHuntsman** [comment]
No, that might be the problem!

**Comment by SnowHuntsman** [comment]
I enabled Molang Features in the world and the tree taps are working! Thank you!
