### ISSUE TITLE
Leaves have missing texture

### ISSUE THREAD

**Issue by kyleplo** [legopitstop/Lots-More-Food-Mods#7]
**What Edition of the mod are you using?**
The Minecraft platform that that issue is taking place: Bedrock

**Describe the bug**
All of the fruit tree leaves do not have a texture, it just shows the missing texture thingy

**To Reproduce**
Find a fruit tree or place some fruit tree leaves

**Expected behavior**
They should have a texture

**Smartphone (please complete the following information):**
 - Minecraft Version: 1.16.200
 - Mod Version: 1.1.6
 - OS: iPadOS

**Comment by legopitstop** [comment]
Leaves are going to be removed from the addon. But thanks for reporting the issue.
