### ISSUE TITLE
Saplings can’t be placed on dirt like blocks

### ISSUE THREAD

**Issue by MONSTROXITY** [legopitstop/Lots-More-Food-Mods#71]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

Can not place saplings on any block

### Steps To Reproduce

1. Tap on any sapling
2. Plant a grass or dirt block
3. Place sapling in the grass or dirt block
... and grow with bonemeal 

### Expected behavior

Sapling should be able to place and grow

### Minecraft Version

V1.20.13

### Mod Version

newer

### Platform

Ios

### Additional context

Found in LotsMoreFood addon

**Comment by legopitstop** [comment]
I've tested v1.7.0-pre5 on iOS and is working for me. If you're still having this issue please provide more details like a video.
