### ISSUE TITLE
Chicken Noodle Soup

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#72]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

When crafting chicken noodle soup, water bucket is removed when the item is crafted. The water bucket should return to players inventory as a empty bucket.

### Steps To Reproduce

1. Go to crafting table.
2. Place 1 water bucket, 2 cooked chicken, large bowl.
3. Craft chicken noodle soup.
4. Water bucket is removed but is not returned with a empty bucket to player's inventory.

### Expected behavior

Once chicken noodle soup is crafted, empty bucket should appear in players inventory.

### Minecraft Version

1.20.15

### Mod Version

Pre 5

### Platform

All

**Comment by legopitstop** [comment]
Fixed in [v1.7.0-pre6](https://more-food.fandom.com/wiki/Bedrock_Edition_1.7.0-pre6)
