### ISSUE TITLE
Saplings Disappearing

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#78]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

In survival mode, when a player has more than 1 more food sapling in their inventory, when placing a more food sapling down on the ground, it removes 2 more food saplings from the players inventory. 

### Steps To Reproduce

1. Have 2 or more of the more food saplings of the same sapling. (Example, 4 apple saplings.)
2. Place one of the more food saplings in the world.
3. A total of 2 of the saplings will be removed from the player's inventory.

### Expected behavior

When player places a sapling down, it only removes 1 sapling from their inventory and no more saplings get removed.

### Minecraft Version

1.20.32

### Mod Version

Pre 5

### Platform

Xbox, PlayStation, Nintendo Switch, PC, Mobile

**Comment by legopitstop** [comment]
Testing this in-game right now.

**Comment by legopitstop** [comment]
I was able to reproduce this issue in-game. It seems to affect saplings, watermint, and spearmint. But doesn't effect Wooden Tree Tap, Chocolate Cake, and bushes.

**Comment by SnowHuntsman** [comment]
Yeah we tested this in our world and also watermint and spearmint is the same. Didn't notice that until you tested it. Thanks for looking into this. :)

**Comment by legopitstop** [comment]
Fixed in [v1.7.0-pre6](https://more-food.fandom.com/wiki/Bedrock_Edition_1.7.0-pre6)
