### ISSUE TITLE
Fertile Soil Side Textures Missing

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#79]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

The side texture of Fertile Soil is missing.
https://i.imgur.com/xkaAprC.png

### Steps To Reproduce

1. 
2. 
3. 

### Expected behavior

Sides of Fertile Soil have the same texture as dirt.

### Minecraft Version

1.20.32

### Mod Version

Pre 5

### Platform

Xbox, PlayStation, Nintendo Switch, PC, Mobile

**Comment by legopitstop** [comment]
This is really weird. It must be because Assets Plus is in the wrong order. Make sure Assets Plus is under LMF but higher than faithful. But if that was the issue I would've expected the side texture to use the black and magnet missing texture instead.

**Comment by SnowHuntsman** [comment]
I have replaced the packs that we use in the following order.
1- LMF
2- Foxy No Tail Mob Heads
3- Assets Plus
4- Faithful 32x

This fixed the issue we was having. Thank you!
