### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by turtlesuwu** [legopitstop/Lots-More-Food-Mods#8]
**What Edition of the mod are you using?**
The Minecraft platform that that issue is taking place:
I'm using 1.16.4 version of the game.
i used Tlauncher to get Minecraft for free and I also use Atenos to create the server

**Describe the bug**
The mod is in. You could see the foods and tools when you go to creative. You could plant the seeds and everything is good until you go make the actual food. When you go to the crafting table to make food nothing happens. I made sure the ingredients and the placement in the crafting table are correct but nothing happens. In the crafting table book where it shows you the recipes to create stuff, non of the foods or stuff from the mode shows up. I don't know if I'm doing something wrong or if its a bug.
**To Reproduce**
1. Go to the crafting table
2. place the ingredients in the crafting table
3. Nothing pops up, it doesn't creat anything

**Expected behavior**
I expected that when you but the ingredients in the crafting table I would be able to creat food with it

**Screenshots**
If applicable, add screenshots to help explain your [problem.]

![2021-01-04_16 45 00](https://user-images.githubusercontent.com/76973732/103582993-eb107d80-4eac-11eb-946d-d1eff1eecca4.png)

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.16.4 ]
 - Mod Version "LotsMoreFood-1.16.4-1.2.0.jar
 - OS: Window 10 home version 1909

**Additional context**

**Comment by legopitstop** [comment]
Are you using the forge edition of the mod?

**Comment by legopitstop** [comment]
Also, note that the screenshotted recipe is for a separate add-on datapack mod called [More Honey.](https://www.planetminecraft.com/texture-pack/lots-more-gold-texture-pack-v2-1-14-1-15/)
