### ISSUE TITLE
Shroomlight Missing Texture When Placed

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#80]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

Shroom light is missing texture when placed in the world.
https://i.imgur.com/xkaAprC.png

### Steps To Reproduce

1. 
2. 
3. 

### Expected behavior

Same texture shown in hot bar is shown when block is placed in the world.

### Minecraft Version

1.20.32

### Mod Version

Pre 5

### Platform

Xbox, PlayStation, Nintendo Switch, PC, Mobile

**Comment by legopitstop** [comment]
Same reason as #79

**Comment by SnowHuntsman** [comment]
Issue fixed by ordering LMF as 1st in the pack order.
