### ISSUE TITLE
Coffee beans give nothing upon harvest

### ISSUE THREAD

**Issue by VirulentSlayer** [legopitstop/Lots-More-Food-Mods#82]
### What Edition of the mod are you using?

Fabric

### Describe the bug

right-clicking on a coffee bean bush will not give coffee beans. The bush must be mined when fully matured to produce 2 coffee beans.

### Steps To Reproduce

1. from coffee bean in ground
2.  right click to harvest once fully grown.

### Expected behavior

expected right click to harvest something, rather than not to harvest anything.

### Minecraft Version

1.20.2

### Mod Version

fabric v.0.0.3 (beta)

### Platform

Java, Windows 11.

**Comment by legopitstop** [comment]
Fixed in [v0.0.4](https://www.curseforge.com/minecraft/mc-mods/lots-more-food-fabric/files)
