### ISSUE TITLE
Nutrition Rebalance

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#83]
### Describe the solution you'd like

We use this pack in a bedrock survival server and crafting a lot of the items can be a challenge for players as making the items can require several items. For example, breakfast muffins. You have to make the muffin, then add the other materials to be able to craft the actual item to eat. If your hunger is very low, this doesn't add much to it.

I'm wondering if a rebalance of nutrition could take place for the items to provide 100% hunger replace for the items, such as sandwiches and other items in which you would be full from eating?

### Is your feature request related to a problem? Please describe.

Not related to a problem.

### Prefered Edition

Bedrock

**Comment by legopitstop** [comment]
Thank you for your submission. This issue is being tracked in #32
