### ISSUE TITLE
Both Raw hamburger and Vegan burger patties are not cooked

### ISSUE THREAD

**Issue by Jia1003** [legopitstop/Lots-More-Food-Mods#84]
### What Edition of the mod are you using?

Fabric

### Describe the bug

If I bake patties, it becomes uncooked patties
![스크린샷(2231)](https://github.com/legopitstop/Lots-More-Food-Mods/assets/152712445/68e86909-9f00-4265-aef0-0fbfe2950225)
![스크린샷(2232)](https://github.com/legopitstop/Lots-More-Food-Mods/assets/152712445/34e3b26c-bf99-4422-84b6-9a07de1a24e7)

### Steps To Reproduce

1. Take the raw patty out of the inventory

2. Bake them in a brazier

### Expected behavior

Please fix these patties so that they can be cooked

### Minecraft Version

1.20.2

### Mod Version

1.20.2

### Platform

Windows 10

**Comment by legopitstop** [comment]
Thank you for your bug report! This issue should be fixed in the next release.

**Comment by legopitstop** [comment]
Fixed in [v0.0.4](https://www.curseforge.com/minecraft/mc-mods/lots-more-food-fabric/files)
