### ISSUE TITLE
Crops Not Growing

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#85]
> ❗❗ This is an issue with Minecraft and not LMF. Please vote for this bug so it can get fixed [MCPE-172035](https://bugs.mojang.com/browse/MCPE-172035) ❗❗

### What Edition of the mod are you using?

Bedrock

### Describe the bug

Lots More Food crops are not growing since the latest Minecraft update.

### Steps To Reproduce

1. Plant a lots more food seed on fertile soil, example used is Garlic.
2. There is no grow stages and the crop remains how it was planted and does not grow.

### Expected behavior

When planted, crop will grow.

### Minecraft Version

1.20.50

### Mod Version

Pre 5

### Platform

All Platforms Impacted

**Comment by SnowHuntsman** [comment]
Berry bushes and fruit trees also impacted.

**Comment by legopitstop** [comment]
Testing this in-game now

**Comment by legopitstop** [comment]
I was able to reproduce this issue, Sadly it's an issue with Minecraft itself so it's out of my hands, For now, you will need to use bone meal to grow your crops.

Someone has already submitted this as a bug if you want to upvote it. Hopefully, it gets patched soon. https://bugs.mojang.com/browse/MCPE-172035

**Comment by SnowHuntsman** [comment]
This was fixed with the latest Minecraft update. Closing this ticket.
