### ISSUE TITLE
Bottle Not Returned - Ice Cream Cone

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#86]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

Bottle is not returned when making ice cream cone.

### Steps To Reproduce

1. Make Ice Cream Cone
2. Bottle is not returned to player

### Expected behavior

When player crafts Ice Cream Cone with vanilla extract, empty bottle should be returned to player.

### Minecraft Version

1.20.50 (Latest)

### Mod Version

Pre 5

### Platform

All

**Comment by legopitstop** [comment]
Fixed in [v1.7.0-pre7](https://more-food.fandom.com/wiki/Bedrock_Edition_1.7.0-pre7)
