### ISSUE TITLE
Jars Not Returned - Jam

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#87]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

When eating jam, jar is not returned

### Steps To Reproduce

1. Eat Jam
2. Jar not returned

### Expected behavior

Jar is returned when jam is applied to product or ate.

### Minecraft Version

1.20.50 (Latest)

### Mod Version

Pre 5

### Platform

All

**Comment by legopitstop** [comment]
Fixed in [v1.7.0-pre7](https://more-food.fandom.com/wiki/Bedrock_Edition_1.7.0-pre7)
