### ISSUE TITLE
LMF Crops Grown on Farm Land

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#88]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

LMF can be grown on farmland and fertile soil

### Steps To Reproduce

1. Plant LMF fertile soil crop seed, example corn, on farm land.
2. It is planted and will grow.

### Expected behavior

Unable to plant on farm land, can only plant the fertile soil crops on fertile soil.

### Minecraft Version

1.20.50 (Latest)

### Mod Version

Pre 5

### Platform

All

**Comment by legopitstop** [comment]
This is the expected behavior for crops. (It avoids confusion when a new player attempts to plant a custom crop)
