### ISSUE TITLE
Sweet Corn Plants Unknown Blocks

### ISSUE THREAD

**Issue by SnowHuntsman** [legopitstop/Lots-More-Food-Mods#89]
### What Edition of the mod are you using?

Bedrock

### Describe the bug

When planting sweet corn, it plants a unknown block.

### Steps To Reproduce

1. Hold Sweet Corn
2. Plant Sweet Corn on Fertile Soil
3. Unknown Block is planted.

### Expected behavior

When planting sweet corn, it should plant a corn crop on fertile soil.

### Minecraft Version

1.20.51

### Mod Version

Pre 7

### Platform

All

**Comment by legopitstop** [comment]
Fixed in [1.7.0-rc1](https://www.curseforge.com/minecraft-bedrock/addons/more-food/files/all?page=1&pageSize=20)
