### ISSUE TITLE
(MCPE) Crafting issues

### ISSUE THREAD

**Issue by Benjimarui** [legopitstop/Lots-More-Food-Mods#9]
**What Edition of the mod are you using?** Bedrock/PE
The Minecraft platform that that issue is taking place: PE

**Describe the bug**
A clear and concise description of what the bug is. A clear and concise description of what the bug is. 
Some items won’t craft in the crafting table. For example when I search up dough to see the recipe it doesn’t show up even if I have all of the ingredients.

**To Reproduce**
1. Go to 'The crafting table'
2. Click on 'search and search ‘dough’’
3. Scroll down to 'nothing pops up'

**Expected behavior**
 I expected to see the dough recipe pop up in the crafting table

**Screenshots**
![7DE817D7-D662-48FE-BCD3-7F8C5539D847](https://user-images.githubusercontent.com/78276492/106366719-e7d1ab80-630b-11eb-8314-33b5f56c19e2.jpeg)
![3404A087-661B-4814-9777-56AF39FBA4F2](https://user-images.githubusercontent.com/78276492/106366721-e86a4200-630b-11eb-84ec-b4e48d018166.jpeg)
![954A1740-8044-40BE-A0F4-FAC0C5C55B24](https://user-images.githubusercontent.com/78276492/106366723-e86a4200-630b-11eb-8417-b9f8c2792b93.jpeg)

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.1.0]
 - Mod Version [e.g. 22]
 - Forge Version [e.g. 35]

**Smartphone (please complete the following information):**
 - Minecraft Version: [1.16.201]
 - Mod Version [1.15]
 - OS: [Android]

**Additional context**

**Comment by legopitstop** [comment]
Is it just the dough. The next version should be fixed.

**Comment by legopitstop** [comment]
Should be fixed in [v1.6.0](https://github.com/legopitstop/Lots-More-Food-Mods/blob/main/Lots%20More%20Food%20Addon/CHANGELOG.md "View Changelog"). You can download the latest version via [MCPEDL](https://mcpedl.com/lots-more-food-bedrock-addon/ "Download via mcpedl.com")
