### ISSUE TITLE
Berry Bushes Do Not Affect Mob Pathfinding

### ISSUE THREAD

**Issue by nexus671** [legopitstop/Lots-More-Food-Mods#90]
### What Edition of the mod are you using?

Fabric

### Describe the bug

I've noticed an issue with the custom berry bushes introduced in this mod. Unlike the vanilla sweet berry bushes, which mobs avoid due to the damage they deal, the custom bushes do not seem to influence mob pathfinding at all. Mobs will walk through them and take damage without attempting to path around.

### Steps To Reproduce

1. Place custom berry bushes from this mod on the ground.
2. Observe mob behavior in proximity to the bushes.

### Expected behavior

Mobs should attempt to path around the berry bushes to avoid taking damage, similar to their behavior with vanilla sweet berry bushes.

### Minecraft Version

1.20.1

### Mod Version

0.0.2

### Additional context

Potential solutions:

Mods avoid the bushes or are only slowed by them.

**Comment by legopitstop** [comment]
Fixed in [v0.0.4](https://www.curseforge.com/minecraft/mc-mods/lots-more-food-fabric/files)
